project_id = "qqkiecshltiqdvfrhgcw"

[functions.google-calendar-auth]
verify_jwt = false

[functions.client-registration]
verify_jwt = false

[functions.sync-to-google-calendar]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.process-message-rules]
verify_jwt = false

